# Dependencias
FROM node:20.9.0-alpine AS deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install


# Builder - Construye la aplicación
FROM node:20.9.0-alpine AS build

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el código fuente de la aplicación (lo que no está definido en el .dockerignore)
COPY . .

ARG AUTH_DATABASE_URL
ENV DATABASE_URL=$AUTH_DATABASE_URL

RUN echo "database_url ::: $AUTH_DATABASE_URL"

RUN npx prisma generate

# RUN npm run test (en caso de realizar tests)
RUN npm run build

RUN npm prune --production

# Crear la imagen final de Docker
FROM node:20.9.0-alpine AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/generated ./generated

ENV NODE_ENV=production

USER node

EXPOSE 3001

CMD ["node", "dist/src/main.js"]